### ISSUE TITLE
Feature: Sortierung und Suche von Dateien in Dateiverwaltungsansicht

### ISSUE THREAD

**Issue by tim-bec** [contao/core#7196]
As editor it would be great to sort and search in the fielmanger.

Currently the situation is a little bit unsatisfying, editors are familiar with search and sort function on file system - even in windows. And baby, its 2014!

So it would be a minor improvement for the great contao DBFS system if its possible to do some, search, filter and sorting in $future.

# Feature

## Sorting

* Alphabetical sorting (as current)
* Z-A sorting
* sort by create
* sort by changed

## Filter
* all
* Just files
* Just files of *.x
* Just folders

## Search
- by filename
- by foldername
- by property
  - filesize
  - dimension
  - types *.x
- In meta-information („where the hell is the 'Lorem ipsum‘ description i liked to replace... ?!")

# Ideas

## DBFS search

> A note is of course necessary, that only files are considered which are in dbfs. 

* we just search in the DBFS
* …for performance
* (for some search / filter we need to improve the DBFS meta-informations)

## DBFS search + filesystem

* like above 
* nothing found in DBFS? Lets take a look in the file-system
* maybe limited to $n levels

**Comment by jenda77** [comment]
+1

**Comment by leofeyer** [comment]
Teil 1 (durchsuchbarer Dateiwähler) implementiert in contao/core-bundle@5f13608eb68f13b8f7d37faa307f6068046f8c38.

**Comment by leofeyer** [comment]
Teil 2 (durchsuchbarer Dateimanager) implementiert in contao/core-bundle@7460493c09169f5792faa99bcb54ea69f679eaf9.

**Comment by leofeyer** [comment]
Now here are the limitations:

* Only synchronized folders are included in the search results
* There are no sorting options, because there is no (performant) way to sort by atime, mtime or ctime
* There is no reverse sorting, because the file manager uses a tree structure (just like the site structure)
* There is no filtering besides being able to search for the file name, path or extension
* There is no way to search for meta information without loading the files model for every (!) search result

**Comment by aschempp** [comment]
Wouldn't it be "way easier" to implement a javascript search on the list element names? Or would collapsed nodes be a problem?

**Comment by leofeyer** [comment]
Collapsed nodes would be a problem for sure.

**Comment by Toflar** [comment]
I think it's strange that it also searches for folders.

Imagine this situation:

* layout
    * img
        * image_1.png
        * image_2.png
    * js
        * script_1.js
        * test.js
    * css
        * layout.css


If you search for "layout", what do you expect to be shown? Personally, I expect only `layout.css` to be shown, however, Contao displays all of the above as I listed them because all of them are in a folder that matches the search input so they're all listed.

**Comment by leofeyer** [comment]
I would expect the following:

* layout
  * css
    * layout.css

But I don't know if the (regex-based) filter can be tuned to be this exact.

**Comment by leofeyer** [comment]
We could also develop a separate view, which only shows the following:

* layout
* layout.css

However, I doubt that this can be done with the current tree.

**Comment by leofeyer** [comment]
Of course, the two posts above only apply to searching for the name. If you search for the file path, it is correct to show `layout/img/image_1.png`, since its path contains "layout".

**Comment by leofeyer** [comment]
Overworked implementation in contao/core-bundle@33002c618174688b007046e6fb69a126d2e2fba4.
