### ISSUE TITLE
Small improvements 

### ISSUE THREAD

**Issue by alarstyle** [contao/core#7422]
I have some suggestions about improvements.

1. Combine Page Picker and File Picker and make just one Picker. And it should work not only with pages and files, but with any table.
You just need to change the logic. Maybe it is possible to use regular view of the table, but instead of showing action icon you can show checkbox or radio.

2. Remove 
`onclick="Theme.toggleSelect(this)"`
Changing checkbox/radio state can be easily done with wrapping blocks into `label`s, and it will work without JS.

3. Remove 
`onmouseover="Theme.hoverDiv(this,1)"`
`onmouseout="Theme.hoverDiv(this,0)"`
`onmouseover="Theme.hoverRow(this,1)"`
`onmouseout="Theme.hoverRow(this,0)"`
It just changing background of elements, it can be done with CSS.

4. In the backend navigation, items always should be in DOM, even if the group is collapsed. It won't make the performance faster or slower, but it will prevent flashing of preloader.

5. Move all html code from drivers (DC_Table, DC_File, DC_Folder) to separate templates. So people can extend this templates.

6. Output website title from settings page in the header of backend. Something like this:
![screen_title](https://cloud.githubusercontent.com/assets/1730120/4914442/86b6f740-64c2-11e4-9c4c-7083af8b3df1.jpg)

7. When debug mode is on, in the backend there is inline style `margin-bottom: 60px;` for `<body>` tag. And it is changing when user toggles debug bar. It can be done with css, just need to add/remove css class in `<body>` tag. This can be useful, for example, if user wants to change look of debug bar or make it higher.

If something is not clear, just let me know and I'll try to explain :)

**Comment by leofeyer** [comment]
We have discussed your ticket on Mumble on January 26th.

1. We don't think this is possible or worth the effort to make it possible.

2. This would require a markup change and thus imply a BC break.

3. This is something we can try.

4. Please make a pull request with the required changes. Make sure that the application correctly remembers the menu state.

5. Right now we cannot foresee the future of the `DC_*` drivers. It is possible that we will be incorporating the `DC_General` extension in one of the next major versions, then the existing drivers would be removed. Otherwise we would refactor this accordingly.

6. Please make a pull request with the required changes.

7. Please make a pull request with the required changes.

**Comment by leofeyer** [comment]
See https://github.com/contao/core/issues/7837 regarding no. 3 and https://github.com/contao/core/issues/7838 regarding no. 4.

Since the requested pull requests have not been created so far, I assume they never will, so I'm closing the ticket.

**Comment by alarstyle** [comment]
Sorry for that, I was overloaded with work for last three months :(
