### ISSUE TITLE
[3.4.0] Startseite nicht als "active"

### ISSUE THREAD

**Issue by verstaerker** [contao/core#7562]
Die Startseite einer Domain wird im FE nur mit der Klasse "active" bzw. dem Objekt-Attribut isActive versehen, wenn der alias "index" ist. In allen anderen Fällen, erhält der Listeneintrag nur die Klasse "trail".

Kann auch auf demo.contao.org erzeugt werden, indem "Home" das Alias "home" zugewiesen wird.

**Comment by leofeyer** [comment]
Ich kann das Verhalten bestätigen, allerdings ist es aus Sicht von Contao korrekt. Wenn das Alias der Startseite `index` ist, wird es weggelassen und das Alias ist de factor leer -> stimmt mit dem Alias bei Aufruf der leeren URL überein. Ist das Alias aber `home`, lautet die URL der Seite `home.html` und stimmt eben nicht mit dem Alias bei Aufruf der leeren URL überein.

**Comment by verstaerker** [comment]
So gesehen ist das natürlich korrekt. Mich hat nur verwirrt, dass der "Home" Eintrag manchmal ein Link war und dann wieder nicht bzw. zwei Zustände annehmen kann.

**Comment by tabcontao** [comment]
Theoretisch korrekt mag es ja sein, aber unter 3.2.16 geht das noch problemlos auch bei anderen Aliasen als "index". Da wird auch bei Alias "home" für die Startseite dem Listenelement die Klasse "active" zugewiesen, was ich in der Praxis auch als "stimmiger" empfinde.

**Comment by lionel-m** [comment]
If we add accented characters in an alias of a page, the main navigation module add  the class `trail` instead of `active` in the link. Example :

```HTML
<li class="trail sibling">
  <a href="spécialisations.html" title="" class="trail sibling" role="menuitem">Spécialisations</a>
</li>
```

Apparently, is it possible to add accented characters in aliases. The regular expression `folderalias` accepts accented characters ? Is it possible to add a test before saving when we insert an alias manually ?

And why it adds the class `trail` in this context...

Tested with Contao 3.4.4

**Comment by leofeyer** [comment]
As discussed on Mumble on May 21st, the simplest solution is to name the alias of your first page "index". It would theoretically be possible to search the database for the first active page, but this would be expensive and decrease the performance; especially because it would need to be done upon every request!

What about adding a warning "your site does not have a page with the alias `index`" as proposed by @aschempp?

**Comment by webdirol** [comment]
Ich habe zwar eine andere Contao Version (4.0.3) aber da es genau um das Thema geht und ich bei Contao 4 dazu nichts gefunden habe postet ich es hier...

Bei mir wird die Startseite bei einem Navigationsmenü leider NICHT mit der Klasse "active" bzw. dem Objekt-Attribut isActive versehen, wenn der alias "index" ist. Wenn ich als Alias z.B. "home" zuweise dann funktioniert es. Ich würde aber lieber "index" für die Startseite verwenden.

Kann es sein dies bei Contao 4.0.3 nicht funktioniert?
