### ISSUE TITLE
Hyperlink empty anchor hash

### ISSUE THREAD

**Issue by tristanlins** [contao/core#7584]
If you input `{{link_url::*}}#` as url in a hyperlink (may be the same for every url input field), the `#` is stripped and the resulting url is `{{link_url::*}}`.
But `{{link_url::*}}#` and `{{link_url::*}}` are two completely different URLs for the browser.

`{{link_url::*}}#` will do a jump to page top.
`{{link_url::*}}` will reload the current page.

`{{link_url::*}}#` is a valid url, I don't see any reason why the empty `#` should be stripped.

Workaround: use `{{link_url::*}}#top` instead of `{{link_url::*}}#`.

**Comment by leofeyer** [comment]
> `{{link_url::*}}#` is a valid url

Really? Even when there are no more characters after the hash?

**Comment by discordier** [comment]
Yep, definitely.

**Comment by tristanlins** [comment]
> Really? Even when there are no more characters after the hash?

Yes, the empty hash `#` is special for "top".

> A URI ending with # is permitted by the generic syntax and could be considered as a kind of empty fragment.

http://en.wikipedia.org/wiki/Fragment_identifier

**Comment by leofeyer** [comment]
The culprit is the PHP `parse_url()` method, which removed the hash if there is no string after it:

https://github.com/contao/core/blob/support/3.2/system/modules/core/library/Contao/Idna.php#L116

So this is rather a PHP bug than a Contao bug, isn't it?

**Comment by cepharum** [comment]
For this might be related to this issue: in Contao 3.4.5 property `imageUrl` isn't working with local-only links used to have on-page navigation. If I try to enter valid relative URL `#some-anchor` to make some image clickable this input is dropped without notice on saving.

In my scenario I use some particular article to fill header of every page. This header is considered containing image to be clickable causing page scrolling back to top. For this article is embedded on every page of website there is no opportunity to qualify the link in `imageUrl` and it might even cause any browser to actually reload page rather than just scrolling.
