### ISSUE TITLE
Duplicate items in the search result (website root, first page)

### ISSUE THREAD

**Issue by x-ray78** [contao/core#7617]
see: https://community.contao.org/de/showthread.php?55358-quot-Startpunkt-einer-Webseite-quot-im-Suchergebnis-nicht-anzeigen

Contao 3.4.3

**Comment by fritzmg** [comment]
After deleting the search index and rebuilding it again, the original behaviour does not occur any more. The problem was, that the start page was present in the index twice:

- once as [demo.contao.org/](http://demo.contao.org/)
- once as [demo.contao.org/en/](http://demo.contao.org/en/)

The former shouldn't even exist in the search index, since it's technically never reachable from the front end, when using the language in the URL (which the Demo does).


May be [demo.contao.org/](http://demo.contao.org/) was in the search index because at one point, some user disabled the language URL, thus [demo.contao.org/](http://demo.contao.org/) became a reachable page and it got indexed this way.

When the Contao demo is reset, is it a truly _complete_ reset?

**Comment by x-ray78** [comment]
Ok, this time rebuilding the search index solves the problem. But there was a problem in the demo and on my installation, so I think there is a bug(?)

**Comment by fritzmg** [comment]
Yeah, now we just have to find out, how this happens.

**Comment by DVeris** [comment]
why my search index has doubles with "?"
for example
- site.com/test/test.html
- site.com/test/test.html?bla

**Comment by leofeyer** [comment]
Any updates on this one?

**Comment by fritzmg** [comment]
The only update I can give you is, that's it happening again on the contao demo: http://demo.contao.org/en/search.html?keywords=About+this&x=0&y=0

**Comment by leofeyer** [comment]
This is just due to the wrong database content in the SQL dump, which is being restored every hour. Once you have rebuilt the search index, the problem is gone. Will fix this in the SQL file.

**Comment by DVeris** [comment]
people!
in search result "?"

for example
test.com/news/news1.html**?**

maybe it files do? 
**?&file**...

**Comment by DVeris** [comment]
i found!!! on official site

https://contao.org/en/search.html?keywords=cms&x=0&y=0&page_s39=6

https://contao.org/en/credits.html?=depth=0=depth=1=depth=2=depth=3=depth=4=endflag
https://contao.org/en/credits.html?a=register*

**Comment by DVeris** [comment]
https://contao.org/en/download.html?o
https://contao.org/en/download.html?cache=off

**Comment by DVeris** [comment]
look on this page (search)
https://contao.org/en/search.html?keywords=cms&x=0&y=0&page_s39=6

**Comment by fritzmg** [comment]
Well, that's not really the reason, those are just two different search results for two different URLs. Which would be the case for demo.contao.org/ and demo.contao.org/en/ - however, there should never be an entry in the search index for demo.contao.org/ since that URL "doesn't exist".

**Comment by leofeyer** [comment]
After updating the SQL dump of the online demo, the problem no longer occurs.

http://demo.contao.org/en/search.html?keywords=About+this
