### ISSUE TITLE
/contao/install.php -> Request Timeout

### ISSUE THREAD

**Issue by DVeris** [contao/core#7680]
virtual hosting
litespeed server
(php 5.4)

Connection Timeout 30 sec

(contao-check - all fine)

```
Request Timeout

This request takes too long to process, it is timed out by the server. If it should not be timed out, please contact administrator of this web site to increase 'Connection Timeout'. 
```

contao 2.11 - all fine
contao 3.2.19 - Request Timeout when installing and when follow the link '/contao/install.php'

**Comment by DVeris** [comment]
Request Timeout occurs after a database is upgraded
tables are created

**Comment by leofeyer** [comment]
Please contact your server administrator. They might be able to track this down by checking the server logs.

**Comment by leofeyer** [comment]
Since a few weeks, the downloads of binary release packages vi GitHub is very slow. They are using Amazon S3 to distribute the files and it sometimes takes 3 or more minutes to complete a download. Since the Contao check uses PHP to download and install Contao, it is subject to the maximum script runtime, which is usually 30 to 60 seconds; not enough time to complete the slow download.

I have already adjusted the Contao check in version 10 to raise the connection timeout as much as possible, but I doubt that this will solve the issue.
