### ISSUE TITLE
Bug/Missing feature in breadcrumb module

### ISSUE THREAD

**Issue by Toflar** [contao/core#7750]
I just had the issue that the first entry of the breadcrumb navigation displayed the right link but the wrong title to it. It links to the first subpage but displays the title of the root page.
This is pretty useless if you have multilingual site structures such as

* Project name (DE)
    * Home (alias: index)
    * About (alias: about)
        * Me (alias: me)
* Project name (EN)
    * Home (alias: index)
    * About (alias: about)
        * Me (alias: me)

because it would generate a breadcrumb menu like this when you are on the page "Me":

    Project name (DE)  >  About  >  Me

However I need it to be

    Home  >  About  >  Me

The funny thing about it all is that the module already takes the first published subpage when it's the root page. See https://github.com/contao/core/blob/master/system/modules/core/modules/ModuleBreadcrumb.php#L77-L90.
The link is correct because it takes `$objFirstPage` here: https://github.com/contao/core/blob/master/system/modules/core/modules/ModuleBreadcrumb.php#L86
However the title is still being taken from the root page: https://github.com/contao/core/blob/master/system/modules/core/modules/ModuleBreadcrumb.php#L87

I named the issue "bug/missing feature" because I don't know if this is intended? Either this is a bug because it should take the title of `$objFirstPage` or I need a checkbox in the module to tell it to also take the title of the first subpage.

Moreover, I have another question: It's impossible to have a page which has no root page as last parent, right? You always must have a root page so `\PageModel::findParentsById($objPage->pid);` will always return a root page as the last entry. Why do we check for `$type == 'root'` here https://github.com/contao/core/blob/master/system/modules/core/modules/ModuleBreadcrumb.php#L78 then? :-D

**Comment by qzminski** [comment]
+1 and I would go with checkbox to preserve BC

**Comment by aschempp** [comment]
This is certainly not a bug, but a problem I had myself. As you certainly noticed, `Home` is not a parent page of `About` in your tree, so your example does not make sense from a technical point of view.

There are currently two solutions:
 1. Move your `About` page into `Home`, effectively making your navigation start at level 2. Obviously, `Home` will then not be part of the main navigation.
 2. Give a better name to your project. I sometimes did that and used our `folderpage` to make the backend more readable.

I don't think taking the title of the first subpage would be a good solution, because it would limit it to your specific case. I would prefer another page title for the navigation/breadcumb if desired (similar to the current `pageTitle` for the `<title>` tag.

**Comment by qzminski** [comment]
We have considered putting that into tl_page, too. However, this setting is very specific to the breadcrumb module which is not always included on the page and thus it might not be a good idea to pollute the tl_page with it.

Technically speaking you are right but on most of the websites all over the web you see the "Home" as a fixed and first point in breadcrumb. This was also the case in at least 90% of my projects. The implementation should be pretty straightforward as all the data is already there and it's a matter of changing two lines of code. This functionality would be **totally optional** (checkbox) so you wouldn't be forced to use it.

Regarding your solutions:
1. Is totally out of question.
2. That would affect the whole website name.
