### ISSUE TITLE
UTF8MB4 support on Contao 3.5

### ISSUE THREAD

**Issue by taca** [contao/core#7794]
Hi,

The install tool of Contao 3.5.RC1 continue to display "Update database tables" when specifying "UTF4MB4" as character set of database (mysqli).

![p 2015-05-02 14 04 22](https://cloud.githubusercontent.com/assets/384611/7440001/f6be55c6-f0d4-11e4-890b-9f2818a87307.png)

Best regards.

**Comment by taca** [comment]
It happens with setting collation to "utf8mb4_unicode.ci".  There is no problem with "utf8mb4_generic_ci".

**Comment by leofeyer** [comment]
On my system, I only get errors about the keys:

![](https://cloud.githubusercontent.com/assets/1192057/7957892/f846b58a-09ea-11e5-82ca-fd328691298b.png)

This is mainly because the key lengths don't match anymore, because all `varchar` fields are still 255 characters long but the index can only be 250 characters long. If you change the `sql` definition in you `dcaconfig.php` file and specify the length of each key (e.g. `index(250)`), the problem is gone.

**Comment by taca** [comment]
What can I change in dcaconfig.php?

**Comment by leofeyer** [comment]
For example:

```php
// Change the key length of tl_files.path
$GLOBALS['TL_DCA']['tl_files]['config']['sql']['keys']['path'] = 'index(250)';
```
