### ISSUE TITLE
Usability impovement of File Picker

### ISSUE THREAD

**Issue by madmaharaja** [contao/core#7841]
Sorry, for putting this into a "new issue" -- it's acutally a feature request, but I wasn't able to figure out how to create a request instead ...

I have the following suggestion to make: In Contao 3 I already found it a major improvement that there is now an fairly easy way to switch from the file picker within the lightbox to the file manager. But from a usability point of view it would seem to be the easiest solution if the file picker directly had all the features that the file manager has. In other words: It would be nice if one didn't have to switch back and forth between file manager and file picker but instead had both functionalities combined. 
Please see the screenshot attached to see visualized what I mean. 
![screenshot-file-select-manager-combined](https://cloud.githubusercontent.com/assets/3133710/7787972/1ab0c45a-0228-11e5-9e2a-ddb4eed6d656.png)

Or is there a huge technical obstacle that's preventing you from already having implemented such a feature?

**Comment by aschempp** [comment]
I think that would it make pretty unclear to the average user what there is to do in the popup.

**Comment by danielhoover** [comment]
I agree with aschempp that it would be too much of functionality for the average user in one lightbox - but I also understand your request, madmaharaja. I'm not really completely happy with the File Picker mechanism either. And some of my clients aren't happy with it too.

I'm currently working on a solution that fits both needs. The thing is, that if you want to select a particular image (for instance Image for a News item) you need to upload it first. That is the logic and process of "contao" and the "File manager". It isn't the logic and process of the user who might think that he has a certain file on his computer that he wants for that specific news item. My idea (to solve this issue) would be to have an additional Button. We would have the Button everyone knows, to trigger the FilePicker and a new Button (or a drop down area of course) to select it from the computer and upload it directly. (I hate wordpress - but I think wordpress has this feature too) This has the consequence that the widget needs to determine to what folder the file(s) should be uploaded to. A solution would be to generate a generic folder to one of the users filemounts if defined (i.e. files/users/username/autoupload/year/month/day/uploaded_filename.suffix) or to the files root (i.e. files/autoupload/year/month/day/uploaded_filename.suffix).

At the moment the implementation (maybe 50% finished) is planned to be an extension - but I wouldn't mind if the core developers find it a solid solution with additional benefit for every user and add it to the core. I use plupload as library/plugin because I also want to combine the feature to resize images on the client side to the max size which is defined for GDImages Width and Height within the contao settings. (some clients just don't understand when I tell them that Files larger than 3000 pixels in width and height are to much for the servers memory - but they know how to pick up the phone and ask me over and over again) And if it is not considered to be valuable for the core - it still would be a nice extension... ;-)

**Comment by jenda77** [comment]
@danielhoover It sounds good. I would prefer your solution because it sounds more userfriendly. Would you like to integrate a solution for the links to the news and events too?
