### ISSUE TITLE
Newsletter: send out Mail to Site Administrator when member unsubscribes

### ISSUE THREAD

**Issue by pswerbung** [contao/core#7893]
When people unsubscribe it generates a log entry. That's fine, but when sending newsletters all few months it would be better to have:
- a clear entry in «newsletter.log» file when users unsubscribe (search&find it later too when the main contao log is deleted)
- parallel send a mail to site administrator with the unsubscription

This way one is able get other adress databases in sync of unsubsciptions.

**Comment by discordier** [comment]
For keeping other databases in sync and/or sending a custom mail, you can use: https://docs.contao.org/books/manual/3.5/en/07-customizing-contao/contao-hooks.html#removerecipient which has been available since TYPOlight 2.8.

I doubt that it conforms to privacy rights if you keep the address "stored" after unsubscription. Storing means in this manner, keeping it in the log file and mailing it to the admin after it has been removed.
If you still need to save the adress somewhere, implement above mentioned hook.
