### ISSUE TITLE
3.5: Use findOneByActivation instead of findByActivation in ModulePassword

### ISSUE THREAD

**Issue by DyaGa** [contao/core#8045]
I think in `ModulePassword` at line [179](https://github.com/contao/core/blob/master/system/modules/core/modules/ModulePassword.php#L179) there should be `findOneByActivation` instead of `findByActivation`. It should return `Model` class object instead of `Collection`

**Comment by leofeyer** [comment]
You are right, but this is in fact a BC break, because we are passing `$objMember` to the "setNewPassword" hook in [ModulePassword.php#L237](https://github.com/contao/core/blob/master/system/modules/core/modules/ModulePassword.php#L237) and we do not know if someone added a type hint for the `Collection` class in their extension.

**Comment by leofeyer** [comment]
This has been changed meanwhile.
