### ISSUE TITLE
Upcoming event list shows incorrect start date for multi day events

### ISSUE THREAD

**Issue by gallien** [contao/core#8194]
Backend:
![backend](https://cloud.githubusercontent.com/assets/812394/12390621/f6792f20-bde1-11e5-8d2f-5093f21f490b.png)

Frontend:
![frontend](https://cloud.githubusercontent.com/assets/812394/12390624/fb859df0-bde1-11e5-8079-92a98d563e26.png)

**Comment by leofeyer** [comment]
This is actually correct. The start time is automatically adjusted to not show a start time in the past. On January 16th, the start day was the 16th but your screenshots have been taken on January 18th, therefore the start day is the 18th.

**Comment by fritzmg** [comment]
This does not make much sense though. If you want to display information of an event on your website, which is currently under way, then you'd still want it to show the given start date and time.

**Comment by Aybee** [comment]
I agree. To me it also looks strange not to see the complete time period of the event. I expected to see the date and time when this event started. Imagin this is e.g. a concert so I want to know how much of the concert I will miss.

**Comment by guido4000** [comment]
It is not correct from a practical standpoint.

**Comment by gallien** [comment]
You are right. We will often show weekend courses from Friday to Sunday on our website. Showing a adjusted start date doesn't make sense. A multi day event starts at start date and not at adjusted start date.

**Comment by thomaspahl** [comment]
I never understood what this shift should be good for. It is a bug in my view. You can hardly explain to your users why the start of a multi-day event is displayed as a moving target. In fact I have to recreate the display values [date, datetime] from the source [startTime] in the event templates, forcing modified templates each time. Furthermore, the implementation is inconsistent, because for a single-day event from 12:00 to 19:00  when read at 17:45 same day the start time is correctly displayed as 12:00 (not as 17:45).
A 2-day event 10.02.2016 12:00 – 11.02.2016 19:00 currently displays as
11.02.2016 18:09 – 11.02.2016 19:00.

BTW, in the EventReader the datetimes shown are correct.

**Comment by leofeyer** [comment]
Related: #153

**Comment by discordier** [comment]
We should definately revert the changes of #153. The current behavior does not make any sense.

**Comment by Toflar** [comment]
As discussed in Mumble on April 21st: The changes in #153 are wrong because they prevent the use case described in this ticket. Therefore, they should be reverted. To achieve the described use case in #153, you can use the recurring events feature.

**Comment by thomaspahl** [comment]
Maybe #6802 is also related.For 3.5.12, see change in https://github.com/contao/core/blob/master/system/modules/calendar/classes/Events.php#L209 ff.
When I move lines 209.. 216 (``//Adjust 6082 ... $intKey =``) down immediately before line 245  (``$until =``), upcoming multi-day events (with and without time, overlapping or not) are displayed correctly (with real startdate even if the event already began) both in `event_upcoming` and `event_full` templates. The ``<time datetime=`` tag still shows the current day instead of the real start day, which perhaps is ok.

I have not seen any problems with this change in other display formats, but surely did not cover all. And I did not knowingly revert any changes by #153.

BTW: The assignment to ``$intDate`` (orig line 215) should be moved down (functionally neutral) to line 365, it is not used before. Moreover, it is superfluous, using ``$intStart`` instead is more logical.

**Comment by leofeyer** [comment]
Reverted in 62b2fb6b5abb6d85d6379fd6bcc8707661ce6026.

**Comment by leofeyer** [comment]
Unfortunately, this change is causing problems: https://github.com/contao/core/issues/8447
