### ISSUE TITLE
sitemap erstellt keine ssl links mehr

### ISSUE THREAD

**Issue by css-umsetzung** [contao/core#8270]
Aktuelle Version 3.5..8

wir benutzen eine contao Installation für zwei Domains.
in der englischen Fassung .com werden noch SSL links in der sitemap generiert,
in der Hauptdomain *.de nicht mehr

Ich gehe davon aus das es daran liegt, dass der Cron unter .de aufgerufen wird?

**Comment by fritzmg** [comment]
I can confirm this. The problem is the following:

`Backend::findSearchablePages` uses the following code:
```php
$feUrl = $objPage->getFrontendUrl();

if (strncmp($feUrl, 'http://', 7) !== 0 && strncmp($feUrl, 'https://', 8) !== 0)
{
	$feUrl = $domain . $feUrl;
}
```
https://github.com/contao/core/blob/3.5.8/system/modules/core/classes/Backend.php#L707

So, whenever `$objPage->getFrontendUrl()` does not return a scheme in its URL (i.e. a relative URL), the current host is added. `$objPage->getFrontendUrl()` always either returns an absolute or a relative URL, depending on the current host. Thus, for the current host, the `useSSL` option of the page is ignored.

Contao should introduce a `generateAbsoluteUrl` function as proposed in contao/core-bundle#458 so that errors like this are less likely to happen. This function would always add the correct scheme and host according to the page's properties.

**Comment by leofeyer** [comment]
Fixed in 354b3a4dfe7d3a341df7767f37b13fc299bad52b.
