### ISSUE TITLE
Class Email /  X-Priority sorgt für 2 Spampunkte bei SpamAssassin

### ISSUE THREAD

**Issue by css-umsetzung** [contao/core#8298]
Durch das setzen von x-Priority springt der SpamAssassin direkt an und gibt der E-Mail direkt 2 Punkte.

Dies ist die Meldung die dann kommt.
**2.0 XPRIO Has X-Priority header**

Es ist auch egal auf was ich den setze, das er gesetzt ist reicht schon aus.
Leider wird X-Priority in der sendTo() Funktion gesetzt, so das man keine Möglichkeit hat, das vor dem Senden über remove() zu entfernen.

Es wäre toll wenn man selbst entscheiden kann ob X-Priority überhaupt gesetzt wird.

**Comment by discordier** [comment]
Why is it present anyway? Outlook compatibility?

**Comment by css-umsetzung** [comment]
SpamAssassin ist ein Serverseitiger Spamschutz den, ich behaupte mal, 90% der Serverbesitzer installiert haben.

https://de.wikipedia.org/wiki/SpamAssassin

Wenn SpamAssasin den X-Priority Header negativ bewertet, dann tun das auch andere Webdienste, ich kenne viele die Ihr SpamLevel auf 3 haben, wenn X-Priority Header bereits 2 Punkte verbraucht, dann ist man aufgrund einer HTML Mail oder anderen Bedingungen, schnell über diesen drei Punkten.

Ziel einer Mail ist es, einem Filter, so unauffällig wie möglich entgegenzutreten.

**Comment by discordier** [comment]
Of course I know SpamAssassin (and am a long time user as well) and run it on all my servers.

I was referring to the header, why that one is present at all, I mean the priority was not meant to be used at all like the way it is used nowadays and IMO does not belong in automated emails from a system (at least not by default).

You see, I am totally with you on the issue, I simply wondered for the reason why it IS there. 
Aside from that, we definately should remove it, yet it is not a bugfix per se but rather getting rid of obsolete information that might cause problems (as it does in your case).
So I do not know if it qualifies to be fixed in 3.5 or rather 4.1 (or even 5.0, if anyone relies on the header, which I strongly doubt).

**Comment by leofeyer** [comment]
Sollte sich das bewahrheiten, habe ich kein Problem damit, die X-Priority zu entfernen. Der Header kommt direkt von SwiftMailer:

https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Mime/SimpleMessage.php#L467-L471

Ich habe allerdings selbst SpamAssassin im Einsatz und hatte noch nie eine Abwertung aufgrund der X-Priority. Wo genau ist das dokumentiert?

**Comment by kikmedia** [comment]
There are actually _some_ reports that mail using the X-Priority-Header may be downvoted in some scenarios (for example https://forums.zarafa.com/showthread.php?12181-X-Priority-Header-from-Webapp-triggers-Spamassassin-Rule, and others). I'm not shure if this is a misconfiguration issue.

But IMHO you should drop the X-Priority (or make it optional) since every mail client suggests a default priority of 3, so the header is completely redundant in most scenarios. I can hardly tell that I _ever_ sent a high priority mail via my CMS.

**Comment by fritzmg** [comment]
> Wo genau ist das dokumentiert?

This is a current list of tests from SpamAssassin: http://www.futurequest.net/docs/SA/
The test in question is called `XPRIO`.

```
XPRIO    meta    Has X-Priority header    1.999
```

**Comment by discordier** [comment]
Defined in SA at https://github.com/apache/spamassassin/blob/d65d063097c80e87cb0b4d9b320e0e8d41fd5410/rules/10_hasbase.cf#L63

@leofeyer the problem is `Swift_Mime_SimpleMessage::setPriority()` is called [here](https://github.com/contao/core/blob/e398ed783a28c840ed01644b7a070b57bf6baf49/system/modules/core/library/Contao/Email.php#L409). Swiftmailer does not set it on it's own apparently.

**Comment by css-umsetzung** [comment]
also der Header kommt so wie ich das sehe ja nur weil du ihn im sendTo() deiner Email Klasse setzt.
$this->objMessage->setPriority($this->intPriority);

wenn er sich selbst setzen sollte könnte er ja auch 
über getHeaders()->remove('X-Priority') deaktiviert werden aber du machst das eben an einem Punkt wo es kein zurück mehr gibt.

**Comment by leofeyer** [comment]
Entfernt in ee4b7f495a7207cb9e30ed7f156ddf0f375eb516.
