### ISSUE TITLE
Page Setting: Redirect Type 301 - SEO error if no redirect page selected (breadcrumb)

### ISSUE THREAD

**Issue by eBlick** [contao/core#8377]
Internal redirect pages need to have a target in the page settings. Otherwise the link in the breadcrumb navigation will be the origin internal page and the redirection triggers after clicking the link.
This causes errors in SEO Site Checks where internal links should not target to a 301-URL.

To select the target upfront seems not to be appropriate because forwarding to the next regular subpage is a common feature.

The links from a forwarded page in the breadcrumb should contain the next regular subpage if no target is selected.

**Comment by leofeyer** [comment]
What exactly is the problem?

**Comment by fritzmg** [comment]
"SEO" wise, this doesn't actually matter, probably.

However, those check tools simply complain, that a link on a page that leads to another page within the same domain, actually response with a 301 redirect pointing to a page, that is also within the same domain. It would be more efficient to link to the redirected page directly.

So imagine a link of a Contao navigation module that says
```html
<a href="foo.html">Foo</a>
```
where in this case, `foo` is a internal redirect page. When you open `http://example.org/foo.html` the webserver (Contao) responds with a `301` status code and redirects you to, say `moo.html`. This is a slight inefficiency, because the link could have pointed to
```html
<a href="moo.html">…</a>
```
right away (in the eye of those SEO site check tools anyway…).

**Comment by leofeyer** [comment]
> the link could have pointed to `<a href="moo.html">…</a>` right away, saving one redirect for the client.

But that's exactly like the navigation menu works already.

**Comment by eBlick** [comment]
Only if a redirect page is selected in the page settings.
If not, it is pointed to „foo“ first and will be forwarded via 301 to „moo“ afterwards.


Am 22.06.2016 um 09:40 schrieb Leo Feyer <notifications@github.com>:

the link could have pointed to <a href="moo.html">…</a> right away, saving one redirect for the client.

But that's exactly like the navigation menu works already.

**Comment by fritzmg** [comment]
> But that's exactly like the navigation menu works already.

Oh, right. Then I don't undestand what @eBlick means.

**Comment by Aybee** [comment]
Go to Demo. Set page Modules to **Internal redirect**. Do **not** choose a **Redirect page**. See breadcrumb in FE. Page Modules links to modules.html but gets redirected to navigation.html.

BTW there is an error with ModuleBooknav which gets included on page navigation.html
> Fatal error: Call to a member function getFrontendUrl() on null in /home/www/system/modules/core/modules/ModuleBooknav.php on line 137

So you have to inactivate this CE first if you want to test.

**Comment by leofeyer** [comment]
Fixed in 45d15a5f6c113399d02bedde3b9ad5b144228834.
