### ISSUE TITLE
Don't create folder if it doesn't exists

### ISSUE THREAD

**Issue by DyaGa** [contao/core#8424]
Use the same logic for folders as for files.

Usage example:

```php
$Folder = new \Folder($strFolder);

if (!$Folder->exists()) {
   $Folder->create(); // Create folder if it doesn't exists
}
```

**Comment by Toflar** [comment]
New features won't make it into Contao 3.5 anymore an in 4 you can just use the SF filesystem component for that. We should deprecate all file system related methods that have a suitable alternative within the SF framework. WDYT @contao/developers?

**Comment by discordier** [comment]
I totally agree with @Toflar that we should deprecate the stuff.
The abstraction of large parts was mainly introduced due to the need of the safe mode hack which got removed anyway.

On the original feature request, this is breaking BC and will definately not make it into a feature release.
I have used `new \Folder('/some/path/I/want/to/ensure/it/exists')` in some places back in the day and therefore all this will break then.

**Comment by aschempp** [comment]
PHPs `SplFileInfo` and Symfony's `SplFileInfo` will probably not provide the same features, but I do agree that they need to be replaced. `File` is a magic collection of stuff I never liked (e.g. generating frontend icons for mime type **from the backend theme**).

**Comment by bytehead** [comment]
I'm for deprecation as well. It would be nice, if we could change to a filesystem abstraction layer (like flysystem) in future.

**Comment by aschempp** [comment]
The first step would be to check which methods already do have a counterpart in Symfony Filesystem and simply already add a deprecation commend and notice to them. Should be an easy pick :-)

**Comment by leofeyer** [comment]
I don't think we need to do this. The replacement for the `Files` classes is a mixture of the Symfony `Filesystem` class, native PHP functions and libraries such as the mime guesser. And since everyone can mostly chose whatever they want, I would simply deprecate the classes and not recommend a specific replacement function.
