### ISSUE TITLE
bug in Install Tool regarding admin creation

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8512]
## Description

If you create an admin account via the Install Tool with a certain password, you will not be able to log in with that password.

## Reproduction

1. Create a fresh Contao `3.5.17` installation or delete any admin accounts from an existing installation.
2. Open and log into the Install Tool.
3. Fill in the database information if necessary.
4. Update the database if necessary.
5. _Create an admin user_ using the following password: `1bjXnG]b<=&[X_hi24Ax`. There won't be any error message and the Install Tool will tell you that _"✔️ An admin user has been created"_. 
6. Go to the Contao back end login and try to log in with the aforementioned password.

The login will fail: `Login failed (note that usernames and passwords are case-sensitive)!`.

**Comment by xchs** [comment]
I was able to reproduce the issue.

**Comment by KaiserCh** [comment]
Just checked: If you use this PW from the backend (create new user or modify existing user), it will work. So it's some sort of escaping-problem with the install tool.

Wild guess without checking:
/system/modules/core/controllers/BackendInstall.php Line 767
Shouldn't it be Input::postRaw() instead of Input::post()?

**Comment by leofeyer** [comment]
Fixed in c155da71338604414e600ac6d7703c2ac000c410.
