### ISSUE TITLE
table records may be deleted while editing them

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8546]
1. log into the Contao demo.
2. create a new content element in the _Home_ article for example. _Do not save or switch type yet_.
3. log into the Contao demo on a different browser or a private browsing window (to simulate another user using the same Contao installation).
4. view the content elements of the _Home_ article.
5. now try to save the new content element in the previous user/session.

This will lead to _An error occurred!_ since the record got deleted by https://github.com/contao/core/blob/3.5.18/system/modules/core/drivers/DC_Table.php#L3168-L3177

**Comment by discordier** [comment]
This is a known issue and has been present since the old TL times.
`reviseTable` cleans all non saved entries of the same user when entering any table view.

It should work when logging in as a different user though.
Have you confirmed that the issue exists when using two different users at the same time?

**Comment by fritzmg** [comment]
You are right, it should only happen with the same user. I only tested it with the same user (k.jones).

**Comment by aschempp** [comment]
This is a known limitation. Every user should only log in once, which usually is not a problem because accounts must be personal.

**Comment by fritzmg** [comment]
Yes, but the same user could have two tabs open in the Contao Backend. But there are even more limitations with that workflow.
