### ISSUE TITLE
Form field "File upload" empty after captcha is answered incorrectly

### ISSUE THREAD

**Issue by madmaharaja** [contao/core#8702]
In forms that contain a file upload field as well as a captcha I've noticed the following problem:
If you select a file, enter a wrong answer into the security question field and then try to submit the form then the file selection is empty again as soon as the alert appears "Please answer the security question!".

After submitting a wrong security question, all other form fields keep the content that previously had been typed in, so in my opinion the file upload field should also remember the selected file. Because what (in our case) happens is that customers who answer the security question incorrectly don't notice that their previously picked file is no longer selected. So they then go on to submit the form without an attachment in the second attempt.

I tested this in two Contao installations (3.5.26 & 3.1) -- unfortunately I couldn't test it in the Contao demo because file upload fields seem to be deactivated there.

**Comment by asaage** [comment]
Due to browser-restrictions [(see)](http://stackoverflow.com/questions/1696877/how-to-set-a-value-to-a-file-input-in-html) this will only be possible if the file is beeing uploaded in the first place which then could clutter up your diskspace with unwanted files from invalid forms.
But you are right - it is inconvenient.
As a workaround you could
a) make the fileupload mandatory or 
b) install the conditionalformfield-extension and display a mandatory fileupload conditionally

**Comment by madmaharaja** [comment]
Thanks for the insight, @asaage! Since I want to keep fileupload optional in our form, I will try option b) that you suggested.

**Comment by KaiserCh** [comment]
A third workaround might be using https://rocksolidthemes.com/de/contao/plugins/honeypot-antispam and completely skip the captcha.

**Comment by madmaharaja** [comment]
Thanks for the recommendation, KaiserCh! I've implemented this solution to all our forms now, e.g.: https://language-boutique.com/request-a-quote.html

**Comment by leofeyer** [comment]
See #5486.
