### ISSUE TITLE
Mehrere  Lesermodule unmöglich / 404-Error

### ISSUE THREAD

**Issue by DesKaisersWein** [contao/core#8725]
Hallo,

Offenbar kann ich nicht mehrere Lesermodule gleichzeitig nutzen.

Zur Klarstellung: In meiner Installation nutze ich die Erweiterungen "Isotope" und auch Nachrichten. Ich habe einen Nachrichtenleser eingerichtet und mehrere Archive, alles funktioniert. Für den Shop hab ich auch einen Produktleser und mehrere Listen erstellt.

Wenn ich nun die Erweiterung "News" in den Einstellungen aktiv lasse, kann ich nicht auf Produktdetails oder meine Bestellungsansicht im Kassenmodul zugreifen, es wird mir immer gesagt "_404 Seite nicht gefunden_". Wenn ich aber diese deaktiviere läuft der Shop einwandfrei. Ich kann also immer nur das als erstes erstellte Lesermodul nutzen. 

Diesen Fehler hab ich auch per Hand nochmal in einer kompletten Neuinstallation nachstellen können:

Contao Version 3.5.27
isotope 	2.4.1
php 5.6 und 7.0

**Comment by fritzmg** [comment]
This is not a bug. As already mentioned [in the forum](https://community.contao.org/de/showthread.php?66956-Contao-News-Isotope-mehrere-Lesermodule-nicht-möglich), you cannot have multiple readers on the same page, accessing the same parameter, since one of them will probably respond with a 404 page.
