### ISSUE TITLE
http Header last-modified wrong

### ISSUE THREAD

**Issue by Metis77** [contao/core#8773]
I just noticed that in Contao 3.5.xx on all Servers I tested the http header last-modified gets generated wrong.
I did not test this on Contao 4.

The last-modified gets always set to the exact time of the request itself.

Why is that?

Maybe the use of last-modified should be disabled in the .htaccess by:
```
<IfModule mod_headers.c>
   Header unset Last-Modified
</IfModule>
```

Or it should be set correctly.

We just had the problem that cloudflare will not cache html with the last-modified header always set to the time of the request.

**Comment by fritzmg** [comment]
As far as I can see, Contao 4.4 does not send a `Last-Modified` header at all.

**Comment by aschempp** [comment]
I can't see anything wrong with that header? If the content was just created, it was actually last modified on the given time?

**Comment by Metis77** [comment]
> If the content was just created, it was actually last modified on the given time?

True, but that exact thing it not happening / working – at least in my tests.

The time of "last-modified" is always the time of the http request itself.
It does not matter, when the content got altered.

If you reload the page, "last-modified" is altered to the current time of this new request.
Can you reproduce it now?

![bildschirmfoto 2017-08-21 um 10 06 55](https://user-images.githubusercontent.com/1408361/29509446-99cd38fc-8658-11e7-9e8c-e2b41f3cd877.png)

**Comment by aschempp** [comment]
It's not about the content date, but when the HTML is generated. The time would only be different if you enable the page cache.

**Comment by Metis77** [comment]
it should be the content date, as far as I understand: 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified

And even with html Caching enabled, this stays the time of the request itself – at least in my tests.
See screenshot: document is cached and loaded from disk, but last-modified is wrong.
![bildschirmfoto 2017-08-21 um 13 01 14](https://user-images.githubusercontent.com/1408361/29516569-2055f04a-8671-11e7-929e-76cd53155e8d.png)

**Comment by fritzmg** [comment]
Quote from the specification:
```
   An origin server SHOULD send Last-Modified for any selected
   representation for which a last modification date can be reasonably
   and consistently determined, since its use in conditional requests
   and evaluating cache freshness ([RFC7234]) results in a substantial
   reduction of HTTP traffic on the Internet and can be a significant
   factor in improving service scalability and reliability.

   A representation is typically the sum of many parts behind the
   resource interface.  The last-modified time would usually be the most
   recent time that any of those parts were changed.  How that value is
   determined for any given resource is an implementation detail beyond
   the scope of this specification.  What matters to HTTP is how
   recipients of the Last-Modified header field can use its value to
   make conditional requests and test the validity of locally cached
   responses.

   An origin server SHOULD obtain the Last-Modified value of the
   representation as close as possible to the time that it generates the
   Date field value for its response.  This allows a recipient to make
   an accurate assessment of the representation's modification time,
   especially if the representation changes near the time that the
   response is generated.
```
Imho, in Contao 3, the `Last-Modified` header should only be set, when the page cache is enabled. Otherwise the date at which the requested resource was last modified cannot be reliably determined in Contao.

**Comment by Metis77** [comment]
> Imho, in Contao 3, the Last-Modified header should only be set, when the page cache is enabled (and then it should use the date at which the cache file of the requested resource was last generated, not just the current date). Otherwise the date at which the requested resource was last modified cannot be reliably determined in Contao.

true.

But still, right now `Last-Modified` does not work, even for page caches sites.

**Comment by KaiserCh** [comment]
If we ignore the possibility to use non-cached insert tags, the fix (for server-cached files) is really easy:

https://github.com/contao/core/blob/977f7ff10d5606f48e97f55d7c39facf114ceedb/system/modules/core/controllers/FrontendIndex.php#L518
https://github.com/contao/core/blob/977f7ff10d5606f48e97f55d7c39facf114ceedb/system/modules/core/controllers/FrontendIndex.php#L525

At this locations, just set the header to:
`header('Last-Modified: ' . gmdate('D, d M Y H:i:s', filemtime($strCacheFile)) . ' GMT');`

But as I said: This only works if we ignore the fact that someone could have done something like {{ua::browser|uncached}} inside the document, maybe in a <script>. In that case, the document would have been modified at delivery time.
To compensate for this, it would be necessary to compare the content of $strBuffer between line 456 and  486. If $strBuffer changed, there were either insert tags or the hook active and the modified time should be the current time.

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by aschempp** [comment]
If I understand the actually issue correctly, it's that CloudFlare *assumes* that if the `Last-Modified` header is the same as the date, the content is always generated on the fly. Therefore it does not make sense to cache it. Because they if cache it, they would use `If-Modified-Since` header for cache busting, but assume that won't work in that case.

Two things come to my mind:
 1. Contao's behavior is not *wrong*, it's technically totally correct
 2. CloudFlare's assumption does make sense to me, even though it can cause unwanted side-effects

Unfortunately, I think the setup of Contao is not really compatible with CloudFlare or any CDN in particular. Because Contao can modify cached HTML on the fly, and for example does so for the browser-specific body classes.

@KaiserCh is actually correct. The `Last-Modified` header can only be set to something else than the current time if the page was cached by Contao and not modified on delivery time. So one would need to modify `fe_page` and remove uncached inserttags for it to work (who uses browser CSS classes anyway 😉 ).

I wonder if we can/should fix this in Contao 3, and how we can/should handle this in Contao 4 …

**Comment by KaiserCh** [comment]
Browser classes can in fact be useful. I had some problems with Safari in the past. But: That's something that could be handled by clientside JS.
On the other hand...
- Contao sends a "vary: User-Agent", so a content change based on browser is defined
- for visitors browsers (not 3rd party caches like CloudFlare, a Varnish server,...), at least the UA-inserttag doesn't matter. It's the same UA, isn't it, maybe with a slight version change due to autoupdate.
- for 3rd party full page caches, it doesn't matter, too. They will create an internal cache based on the "vary"-header, listing multiple cache results for multiple UAs. At least, if configured properly.

Uncached tags are a PITA anyway, as many of them don't work correctly in Contao 3. See #8643 

> There are only two hard things in Computer Science: cache invalidation and naming things.
-- Phil Karlton

**Comment by Toflar** [comment]
All of it is handled properly in Contao 4. Uncacheable insert tags are rendered as ESI and all in all it is way more optimized for reverse proxies and will continue to improve in doing so 😄  You'll get much better caching results if you update to Contao 4 for sure!
So it's probably not worth dealing with these issues in 3.5 but update right away instead and see if you still have the same issues. If so, I'm sure we can fix that (which I would love to do but for 3.5 I don't really care anymore because the whole caching implementation is nonsense and stuff probably can't be fixed anyway).

**Comment by Metis77** [comment]
I also would tend to keep it simple for contao 4.
Why not just dont use/set the last-modified header?

**Comment by fritzmg** [comment]
> and how we can/should handle this in Contao 4 …

Currently it does not set the header anyway.

**Comment by leofeyer** [comment]
> We just had the problem that cloudflare will not cache html with the last-modified header always set to the time of the request.

As discussed in Mumble on October 5th, we think that this – if it is true at all – is a Cloudflare bug. Any reverse proxy we know uses caching headers such as `cache-control` or `expires` to determine whether a response can be cashed or not.

Maybe the `Vary: User-Agent` header prevents Cloudflare from caching the response?

Anyway, using a reverse proxy with Contao 3 is cumbersome. All these problems are fixed in Contao 4, so you should probably consider upgrading.
