### ISSUE TITLE
News or Event -Datail : Alias with "Umlaute" don´t work

### ISSUE THREAD

**Issue by kgansberger** [contao/core#8802]
demo.contao.org: try to give event or news detailpage an site - alias with ü. 

![](https://user-images.githubusercontent.com/1192057/32238287-b68a067c-be67-11e7-82bb-c65d77ae3f4f.png)

```
Warning: sprintf(): Too few arguments in /home/www/releases/13/vendor/contao/calendar-bundle/src/Resources/contao/classes/Calendar.php on line 371

Warning: sprintf(): Too few arguments in /home/www/releases/13/vendor/contao/news-bundle/src/Resources/contao/classes/News.php on line 477
```

**Comment by Samson1964** [comment]
Endlich bekommen die Alias-ohne-Umlaute-und-Sonderzeichen-Verfechter wieder etwas Wind in die Segel ;-)

**Comment by kgansberger** [comment]
ich will da keinen Streit vom Zaun brechen :|

**Comment by leofeyer** [comment]
Ich konnte das Problem nicht reproduzieren in der Onlinedemo. Wie genau hattest Du das gemacht?

> ich will da keinen Streit vom Zaun brechen :|

Keine Sorge. Wir hatten das für die 4.4 so festlegen müssen und @ausi hat dafür gesorgt, dass in der 4.5 jeder selbst entscheiden kann (siehe contao/core-bundle#1016), insofern gibt es keinen Grund für Streit.

**Comment by kgansberger** [comment]
komisch. ich kanns selber nicht mehr nachstellen. Fakt ist, dass ich nach dem Speichern obigen Fehler erhalten habe, sowohl in meiner lokalen Installation sowie in der Onlinedemo.

**Comment by gmpf** [comment]
In order to produce this error for News, `News->generateFiles()` or `News->getSearchablePages()` must be called. I found this path to reproduce the error in the demo via sitemap XML generation:

1. Edit the website root
2. Activate "Create an XML sitemap" and set a file name, e. g. "sitemap". Save.
3. Edit the news detail page and add an "ü" to the alias. Save.

This probably occurs because `News->getLink()` is called with a parameter `$strUrl` that is supposed to have just `/%s` or `/items/%s` in it for later replacement using `sprintf()`: [1]
```php
// News->getSearchablePages()
$arrProcessed[$objArchive->jumpTo] = $objParent->getAbsoluteUrl(\Config::get('useAutoItem') ? '/%s' : '/items/%s');
[…]
$strUrl = $arrProcessed[$objArchive->jumpTo];
[…]
$arrPages[] = $this->getLink($objArticle, $strUrl);

// News->getLink()
return sprintf($strUrl, ($objItem->alias ?: $objItem->id));
```

However, with special characters in the alias, `$strUrl` has more than one % in it due to URL encoding:

`getAbsoluteUrl()` is a `PageModel` method. In Contao 3.5, `PageModel->getAbsoluteUrl()` used `Controller::generateFrontendUrl()`. That method returned a non-encoded URL, so nothing broke at this point. In 4.4, `PageModel->getAbsoluteUrl()` uses `Contao\CoreBundle\Routing\UrlGenerator`, which uses Symfony's URL generator, creating an encoded URL.

So if you have an "ü" in the alias, that gets encoded to "%C3%BC", and now there are three % in `$strUrl`, including the intended `%s`, which causes the `sprintf()` problem.

---
[1]
- https://github.com/contao/news-bundle/blob/f88ba5ca64f391d966c7da169d3f5078e7a79efd/src/Resources/contao/classes/News.php#L332
- https://github.com/contao/news-bundle/blob/f88ba5ca64f391d966c7da169d3f5078e7a79efd/src/Resources/contao/classes/News.php#L335
- https://github.com/contao/news-bundle/blob/f88ba5ca64f391d966c7da169d3f5078e7a79efd/src/Resources/contao/classes/News.php#L344
- https://github.com/contao/news-bundle/blob/f88ba5ca64f391d966c7da169d3f5078e7a79efd/src/Resources/contao/classes/News.php#L477

**Comment by ausi** [comment]
I think this can be fixed by escaping the `%` characters:

```php
return sprintf(preg_replace('/%(?!s)/', '%%', $strUrl), ($objItem->alias ?: $objItem->id));
```

@gmpf can you verify that this fixes the issue?

**Comment by chriza** [comment]
Der Fehler tritt auf, wenn eine veröffenlichte Nachricht im Archiv mit einer Weiterleitung auf eine Umlautseite vorhanden ist.

**Comment by leofeyer** [comment]
Behoben in Contao 4.4.9.
