### ISSUE TITLE
Backend css rule for class .w50 not working for checkboxes

### ISSUE THREAD

**Issue by lumas-consulting** [contao/core#8864]
Checkboxes need sometimes more space.
When using .w50 Class for custom backend elements the checkbox is limited to 80px height.
We should use a min-height: 80px instead.

<img width="373" alt="bildschirmfoto 2018-03-13 um 08 23 17" src="https://user-images.githubusercontent.com/6641281/37327752-d99b412e-2697-11e8-96d9-0121e7e5086d.png">

![image_1325](https://user-images.githubusercontent.com/6641281/37327693-a069e02c-2697-11e8-8493-eec44855c3ab.png)

**Comment by fritzmg** [comment]
You should use w50 only for single ones. Or use tl_style => 'height:auto'.

**Comment by lumas-consulting** [comment]
Why build a workaround with inline-styles? What's the problem with a CSS change that would work in general?

**Comment by leofeyer** [comment]
If we can be sure that `min-height` works in all browsers and does not cause any side-effects, I'd be in favor of this solution.

**Comment by Aybee** [comment]
And again it seems to be time for a flexbox solution.

**Comment by lumas-consulting** [comment]
THX

**Comment by leofeyer** [comment]
> If we can be sure that `min-height` works in all browsers and does not cause any side-effects

Did anyone test this?

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by lumas-consulting** [comment]
as far as I am concerned it worked in safari, firefox and chrome in osx environment.

**Comment by leofeyer** [comment]
We need some more people to test this please. @frontendschlampe @may17 @fritzmg @cliffparnitzky @ausi @Pellinger @netzarbeiter /cc

**Comment by fritzmg** [comment]
In general this works. Here are two screenshots from Contao 4.5 from FireFox and IE 11 under Windows 10 x64:

![w50ff](https://user-images.githubusercontent.com/4970961/45219125-2cc39600-b2aa-11e8-95ee-eb1e226cd127.png)

![w50ie11](https://user-images.githubusercontent.com/4970961/45219105-1a495c80-b2aa-11e8-8889-214166ad6f92.png)

In this test I added the `w50` class to all the widgets within the _Stylesheets_ section of the page layout and changed the `height` of `.w50` to `min-height`.

Since the height of one `w50` element can now be anything, the resulting layout may look a little off, since you will not know how many elements will float to the right (or left) of the `w50` element. This may result in some whitespace in odd places - as seen above.

**Comment by may17** [comment]
min-height has full browser support see https://caniuse.com/#feat=minmaxwh

**Comment by cliffparnitzky** [comment]
I can confirm the test of @fritzmg : used Contao 4.4 in Chrome, Firefox and IE 11

**Comment by leofeyer** [comment]
Changed in contao/contao@a3f4e867aaa57e21927a45ba9b3846a6369c169f.
